### ISSUE TITLE
Fix release & usage flow

### ISSUE THREAD

**Issue by itaibenda** [wix-incubator/puppeteer-compare#4]
`npx site-recorder` should install and run the CLI

Also:
* Update the usage README accordingly (shouldn't be `npm i` and then `site-recorder`)
* Add docs for all the CLI options

**Comment by Cwallice** [comment]
done in https://github.com/wix-incubator/site-recorder/commit/e0aa9be6dbd3f90485ce5c7cd76169fa4f7d1fb0
