### ISSUE TITLE
Add custom puppeteer script

### ISSUE THREAD

**Issue by itaibenda** [wix-incubator/puppeteer-compare#5]
Instead of just rendering the page here: https://github.com/wix-incubator/site-recorder/blob/master/src/puppeteer-trace-with-screeshots.js#L39

Support a custom script that does the navigation and possibly other actions (clicks, more navigations, etc).
This could possibly be implemented using another parameter with a script that exports a function like:
```javascript
/*
page: puppeteer page object
*/
export default async function customNavigation(page, url) {
  await page.goto(url, {waitUntil: 'networkidle2'});
  await page.evaluate(() => window.getElementBy('#button').click());
  await page.waitForSelector('#second-view');
  ...
}
```

**Comment by Cwallice** [comment]
done in https://github.com/wix-incubator/site-recorder/pull/9/commits/3ba8af266062e861f4c28f4f1dcbd5e03590612e
